### ISSUE TITLE
Slip Day Tracker

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#36]
v0.5 of an automated slip day tracker works!

http://alonzo.herokuapp.com/slipdays/<sid>

In HipChat
"@ Alonzo get slip days <sid>"

There is a problem:
- [x] The first request works fine, but subsequent requests don't seem to be answered. (Rate limits?)
- [x] We still need a way to override the automatic calculations
    - Idea: Readers specify a specific comment on a submission to correct for slip days:

    >    Slip Day Adjustment: -1 day

- [x] This does NOT use Data from Piazza
    - May not be so problematic if we use bCourses for IPT or if we have easy to do adjustments.
- [x] Grace period should be more configurable (and specified in minutes)
- [x] Web endpoint should return JSON
- [x] People over 3 slip days should get a warning message
- [x] if possible we should show the deductions for students over 3 (or N) days. -- this will save grading time.

**Comment by cycomachead** [comment]
Fixed
